version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
      - REPOSITORY_URI=127083894006.dkr.ecr.us-east-1.amazonaws.com/hello-world-rest-api:${TAG}
  build:
    commands:
      - echo Build started on `date`
      - echo $REPOSITORY_URI
      - mvn clean package -Ddockerfile.skip
      - docker build --tag $REPOSITORY_URI .
  post_build:
    commands:
      - printenv
      - echo Build completed on `date`
      - echo $(docker images)
      - echo Pushing docker image
      - docker push $REPOSITORY_URI
      - echo push completed
      - printf '[{"name":"aws-hello-world-rest-api","repositoryUri":"%s"}]' $REPOSITORY_URI > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
